### ISSUE TITLE
Uncaught ReferenceError: autoScroll is not defined

### ISSUE THREAD

**Issue by rohan-deshpande** [hollowdoor/dom_autoscroller#10]
Heya so I am working on a non-ES6 project right now and wanted to use this lib. I noticed that there is no bower package yet so I just installed via npm and piped the `node_modules/dom-autoscroller/dist/dom-autoscroller.js` into my gulpfile. 

When I try to call the `autoScroll` method, I get the above error.

**Comment by hollowdoor** [comment]
The global reference to it is named **autoScroller**. Which is different than **autoScroll** in the docs. Should I change the name for the stand alone build?

**Comment by rohan-deshpande** [comment]
Ah I see, hmm yeah I found that very confusing. Definitely make the global function the same for the browser build.

I'm correct in assuming that the files in dist are to work without using browserify/webpack or `require` right?

**Comment by hollowdoor** [comment]
Yes. Those are for script tags. I'll get to changing the name sometime today.

**Comment by hollowdoor** [comment]
The name is updated to match the docs. Hopefully this doesn't break too many dev work flows out there.
