### ISSUE TITLE
Scrolling speed behavior

### ISSUE THREAD

**Issue by 1j01** [hollowdoor/dom_autoscroller#11]
Currently the scrolling speed increases based on the number of mousemove events in the scroll area, apparently because it accumulates many setTimeouts.

Instead the speed should be based on the distance to the edge within the margin. This is what browsers, operating systems etc. do because it lets the user control the speed in a meaningful way. 

After checking out this library's demo, I've implemented the desired behavior in my [audio editor Wavey](https://github.com/1j01/wavey).
Here's the relevant code extracted (and modified a bit) (in [CoffeeScript](http://coffeescript.org/)):

``` coffee

auto_scroll_margin = 30
auto_scroll_max_speed = 20

auto_scroll_container_el.addEventListener "mousedown", (e)->

    auto_scroll_container_rect = auto_scroll_container_el.getBoundingClientRect()
    auto_scroll_rect =
        left: auto_scroll_container_rect.left
        top: auto_scroll_container_rect.top
        width: auto_scroll_container_el.clientWidth
        height: auto_scroll_container_el.clientHeight
        right: auto_scroll_container_rect.left + auto_scroll_container_el.clientWidth
        bottom: auto_scroll_container_rect.top + auto_scroll_container_el.clientHeight

    mouse_x = 0
    mouse_y = 0
    auto_scroll_x = 0
    auto_scroll_y = 0
    auto_scroll_animation_frame = -1

    auto_scroll = ->
        auto_scroll_x =
            if mouse_x < auto_scroll_rect.left + auto_scroll_margin
                Math.max(-1, (mouse_x - auto_scroll_rect.left) / auto_scroll_margin - 1) * auto_scroll_max_speed
            else if mouse_x > auto_scroll_rect.right - auto_scroll_margin
                Math.min(1, (mouse_x - auto_scroll_rect.right) / auto_scroll_margin + 1) * auto_scroll_max_speed
            else
                0

        auto_scroll_y =
            if mouse_y < auto_scroll_rect.top + auto_scroll_margin
                Math.max(-1, (mouse_y - auto_scroll_rect.top) / auto_scroll_margin - 1) * auto_scroll_max_speed
            else if mouse_y > auto_scroll_rect.bottom - auto_scroll_margin
                Math.min(1, (mouse_y - auto_scroll_rect.bottom) / auto_scroll_margin + 1) * auto_scroll_max_speed
            else
                0

        # <update selection while scrolling here>

        setTimeout ->
            auto_scroll_container_el.scrollLeft += auto_scroll_x
            auto_scroll_container_el.scrollTop += auto_scroll_y

        auto_scroll_animation_frame = requestAnimationFrame(auto_scroll)

    window.addEventListener "mousemove", onMouseMove = (e)->
        mouse_x = e.clientX
        mouse_y = e.clientY
        cancelAnimationFrame(auto_scroll_animation_frame)
        auto_scroll_animation_frame = requestAnimationFrame(auto_scroll)

    window.addEventListener "mouseup", onMouseUp = (e)->
        window.removeEventListener "mouseup", onMouseUp
        window.removeEventListener "mousemove", onMouseMove
        cancelAnimationFrame(auto_scroll_animation_frame)

```

**Comment by hollowdoor** [comment]
I'll investigate it.

This line here embodies the math you're suggesting?:

``` coffeescript
Math.max(-1, (mouse_y - auto_scroll_rect.top) / auto_scroll_margin - 1) * auto_scroll_max_speed
```

And cancel every move to prevent building up extra calls?:

``` coffeescript
        cancelAnimationFrame(auto_scroll_animation_frame)
        auto_scroll_animation_frame = requestAnimationFrame(auto_scroll)
```

I might have to make this a version 2 change. It could be breaking (surprising) for some people.

Also I can't tell the difference. Drag scrolling in my local text editor acts nearly the same. :)

I get what you're suggesting though.

**Comment by 1j01** [comment]
Yeah. To see how the current behavior is counterintuitive, (on the demo, where scrolling outside is disabled) drag outside the container and back carefully. It'll be slow; then move a bit further onto the container and it starts to pick up speed, then move further and it stops instantly because the cursor left the scroll area.

**Comment by hollowdoor** [comment]
Ok. I see. It's more precise control based on what a user knows.

**Comment by hollowdoor** [comment]
Wow! I just implemented this locally. It works! And it's really freaking smooth too. Way smoother than the original.

I still have to make it compatible with some of the options, and update the readme. This change will be in the next version though.

I'll also need to polyfill requestAnimationFrame for older browsers, but that's not too big of a deal. I think requestAnimationFrame is contributing to the smoothness.

Thank you so much for the suggestion.

**Comment by hollowdoor** [comment]
@1j01 I'm getting ready to document this change before I push. Here you have `auto_scroll_max_speed` that controls the speed. How should I word this for the documentation. Would `speed` in this sense be _pixels per frame_ as opposed to _pixels per second_?

I mainly ask because during testing a max speed of 5 appears to be much faster than 5 pixels per second. The max requestAnimationFrame speed is 60FPS. From the math (mousex/y - distance from edge / margin) \* maxSpeed there is a distance produced. So if the distance is 5 on a frame that would be 5 pixels moved on a frame. 60*5=300pixels per second? I'm having trouble finding a delta.

Even a max speed of 2 is relatively fast. Maybe it's an intuitive number like approx 5 pixels depending on how fast a computer is?

Something else that's interesting. A max speed of one prevents all scrolling. Do you think I should I round up?

**Comment by 1j01** [comment]
Yes, that would be pixels per frame.

In my implementation I can set `auto_scroll_max_speed` to `1` and still have it move.
If you push the changes I can take a look at what's different.

**Comment by hollowdoor** [comment]
Thanks again. I'll check my code once more before I push to see if I changed something. I pretty much just cut up the code you provided, and spliced it into the autoscroller code. I might have screwed up something in the process. If I don't find anything I'll still push.

**Comment by 1j01** [comment]
Oh, on further investigation, it doesn't behave correctly on the right/bottom sides, so I think my math _is_ off, and probably does need some rounding. The left/top sides are probably benefiting from implicit rounding. The right/bottom probably need a floor or ceil and the left/top could use the opposite but don't need it, except for consistency.

**Comment by 1j01** [comment]
Sorry if I sent you on a wild goose chase, you were right that it just needs to be rounded up.

I've updated my code:

``` coffee
auto_scroll_x =
    if mouse_x < auto_scroll_rect.left + auto_scroll_margin
        Math.floor(Math.max(-1, (mouse_x - auto_scroll_rect.left) / auto_scroll_margin - 1) * auto_scroll_max_speed)
    else if mouse_x > auto_scroll_rect.right - auto_scroll_margin
        Math.ceil(Math.min(1, (mouse_x - auto_scroll_rect.right) / auto_scroll_margin + 1) * auto_scroll_max_speed)
    else
        0

auto_scroll_y =
    if mouse_y < auto_scroll_rect.top + auto_scroll_margin
        Math.floor(Math.max(-1, (mouse_y - auto_scroll_rect.top) / auto_scroll_margin - 1) * auto_scroll_max_speed)
    else if mouse_y > auto_scroll_rect.bottom - auto_scroll_margin
        Math.ceil(Math.min(1, (mouse_y - auto_scroll_rect.bottom) / auto_scroll_margin + 1) * auto_scroll_max_speed)
    else
        0
```

**Comment by hollowdoor** [comment]
Haha. :)

I had to make time to work on this so I haven't yet chased the wild goose.

Hopefully I can push version 2 by tomorrow. This particular update will make this library work much nicer.

**Comment by hollowdoor** [comment]
I haven't pushed version 2, but I've updated the demo.

https://jsfiddle.net/hollowdoor/a2or8sez/11/

Almost ready to push. A few more checks, and everything should be ready.

I decided to use es2015 this time around.

**Comment by 1j01** [comment]
I think there's a bug where if you drag it outside and back in occasionally it won't scroll, and then it can start working again while you're still dragging it. I don't know how to consistently reproduce it.

**Comment by hollowdoor** [comment]
I think that is actually an old bug. It doesn't have anything to do with these modifications. The problem for what you're talking about also happens when the pointer crosses containers. It has to do with this library taking multiple elements. For some reason the prevention of scrolling is more pronounced after the change to this scrolling behavior.

I'm going to see if I can solve it. I think I have an idea. If I can't find the problem I'll push, and post another issue.

**Comment by hollowdoor** [comment]
I found what caused the inconsistent scrolling issue in the demo. It's a conflict with dragula. dragula appends the currently dragged element onto the body.

This is a problem because dom-autoscroller seeks through element parents if the current target is a child. Seeking to the body subverts the scrolling behavior. Even if it is dragula that's doing it there could be some other lib that will interfere in a similar way.

I'll just fix the problem instead of starting a new issue.

Version 2 is going to be much better. :)

**Comment by hollowdoor** [comment]
The demo is updated, and it's super nice. By accident fixing the problem with inconsistent scrolling also made it even smoother.

https://jsfiddle.net/hollowdoor/a2or8sez/12/

I want to do some source cleaning then I'll push.

The only problem is if you cross a margin sideways that sometimes prevents scrolling. I would prefer to fix that later.

**Comment by hollowdoor** [comment]
Closing because:

This commit https://github.com/hollowdoor/dom_autoscroller/commit/37cebb240bf6ebbf50793095137868fcf5f01e5b

And this commit https://github.com/hollowdoor/dom_autoscroller/commit/b8b1ab00092587191266006733ef797acdafbea1

@1j01 Thanks. You were a tremendous help.
