### ISSUE TITLE
Update demo link in readme to match newest version

### ISSUE THREAD

**Issue by hollowdoor** [hollowdoor/dom_autoscroller#15]
Like in the title. There's a few bugs in the old demo.

**Comment by 1j01** [comment]
It should also reference the library via an external script via rawgit or unpkg, and link should probably be at the top of the readme.

**Comment by hollowdoor** [comment]
Here's the new demo http://jsfiddle.net/gh/get/library/pure/hollowdoor/dom_autoscroller_demo/tree/master/Demo

It doesn't appear to work unless you click run in the fiddle.

I have yet to put it in the readme because I'm working on the issue #14

**Comment by hollowdoor** [comment]
Strange. The console say's dragula is undefined when ran from loading the url.

**Comment by hollowdoor** [comment]
Whoops I'm tired, and accidentally clicked close.

**Comment by hollowdoor** [comment]
All done. The demo link is not at the top, but I moved it up. It's now under the Install section. There was some problem with the external assets not linking before the fiddle body. I had to include the links in the HTML. Either way it works now.
