### ISSUE TITLE
Build files in dist folder are not working

### ISSUE THREAD

**Issue by MartinSvarrer** [hollowdoor/dom_autoscroller#18]
getClientRect function throws an exception in dependecy 'dom-plane', makes dist build files unusable.

Always throws exception when DOM element is provided, because of `rext.x` typo. (should be `rect.x`).

![image](https://cloud.githubusercontent.com/assets/3289674/20270995/85834720-aa89-11e6-9cc8-be0faa2caf69.png)

**Comment by hollowdoor** [comment]
`dom-plane` is fixed. Going to get ready to push `dom_autoscroller`.

**Comment by hollowdoor** [comment]
Ok fixed.
