### ISSUE TITLE
Bower version

### ISSUE THREAD

**Issue by IvanCoronado** [hollowdoor/dom_autoscroller#19]
Since you can't version your project with bower version [(bower spec)](https://github.com/bower/spec/blob/master/json.md#name).
Can you please create a tag with last version so we can install it with `bower install dom-autoscroller#2.2.6 --save`?
Thanks in advance.

**Comment by hollowdoor** [comment]
It has the latest version tag v2.2.6. I'm still totally unfamiliar with bower. Is there something extra I might need to do in order to have it work?

See issue #9

**Comment by IvanCoronado** [comment]
Bower deprecated version parameter https://github.com/bower/spec/blame/master/json.md#L71-L75

Now bower automatically detects repository tags, but you aren't creating tags with each version. You just need to create a tag for each verion that you release https://help.github.com/articles/working-with-tags/

**Comment by hollowdoor** [comment]
I recently got a new computer, and cloned this repo to my local machine. After looking around it turns out tags are not pulled in with the clone. Do you think this might be part of what's causing the problem?

`git tags` is showing
v2.2.2
v2.2.3
v2.2.4
v2.2.5
v2.2.6

**Comment by IvanCoronado** [comment]
![a](https://cloud.githubusercontent.com/assets/13351933/20392844/e2704bb6-acd9-11e6-9fa2-55145539c404.png)
Your github project hasn't any release or tag

**Comment by IvanCoronado** [comment]
Check this for upload your tags http://stackoverflow.com/questions/5195859/push-a-tag-to-a-remote-repository-using-git

**Comment by hollowdoor** [comment]
I pushed all the tags. Sadly because of my ignorance tags before v2.2.2 did not get updated. :(

**Comment by IvanCoronado** [comment]
Nice! thanks you 👍 

I think that you can still recover that from your git history, tags are just different name for a commit.

**Comment by IvanCoronado** [comment]
I did a PR, if you want update info and remove useless version parameter from bower file
https://github.com/hollowdoor/dom_autoscroller/pull/20

**Comment by hollowdoor** [comment]
Ok. Do you think this can be closed now? Even though old version tags have been lost.

**Comment by IvanCoronado** [comment]
Yes, you don't need care about bower anymore (while you upload tags version).

If you want recover old tags, you can create new tags from old commits. But you can close this issue.

**Comment by hollowdoor** [comment]
For the sake of records I used the advice from here http://stackoverflow.com/questions/3745135/push-git-commits-tags-simultaneously

Using `git config --global push.followTags true`.
