### ISSUE TITLE
Does it work with horizontal scroll?

### ISSUE THREAD

**Issue by glauberramos** [hollowdoor/dom_autoscroller#30]
I am trying to do it in my app but it is not working. And there is no example anywhere that I could find.

**Comment by hollowdoor** [comment]
Yes it should. It's default behavior. What browser are you using? Can you show some code?

**Comment by glauberramos** [comment]
I can't share the code =/. If it works I will do some investigation on my side to see what is the problem. Thanks

**Comment by hollowdoor** [comment]
Cool. I'm going to assume you can't show code because of work. If you continue to have problems you might consider posting a jsfiddle from home. I'll probably take a look myself at testing later this week. The jsfiddle example is broken too so I'll I need to fix that any way.
