### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by chrisl8888** [hollowdoor/dom_autoscroller#4]
Is this MIT licensed? If so i can provide a pull request to add the license.

And also, is it possible to get this repository tagged with versions?

**Comment by hollowdoor** [comment]
Yes it is MIT licensed. I'll look at tagging after your pull request.

**Comment by hollowdoor** [comment]
About when will you do the pull request? I was just wondering. No hurry.

**Comment by hollowdoor** [comment]
From now on I'll update the version with `npm version`. This will auto tag the repo. I should have been doing this before, but old habits die hard.
