### ISSUE TITLE
Bower?

### ISSUE THREAD

**Issue by rohan-deshpande** [hollowdoor/dom_autoscroller#9]
Would you mind creating a bower package for this lib?

**Comment by hollowdoor** [comment]
I don't know. I've never used bower. Let me look at what it takes.

**Comment by rohan-deshpande** [comment]
It's really simple, just create a bower.json file and publish the package. I'd have done it myself but I think it's better for the repo owner to register it.

**Comment by hollowdoor** [comment]
Ok. I can do it. I would like to figure out the other issue with the build first.

**Comment by rohan-deshpande** [comment]
Ok

**Comment by hollowdoor** [comment]
Actually if you want you can make a PR with the bower package info. I can then publish it from my end. I don't have bower installed, but that would surely be easy. If you don't want to do a PR I'll still make the package, but you'll have to wait a little longer.

**Comment by rohan-deshpande** [comment]
Just need to create a `bower.json` file like so:

```
{
  "name": "dom-autoscroller",
  "version": "1.4.0",
  "description": "Auto scroll dom elements",
  "main": "dist/dom-autoscroller.js",
  "keywords": [
    "scroll", "scroller", "autoscroll"
  ],
  "authors": [
    "Quentin Engles"
  ],
  "license": "MIT",
  "homepage": "https://github.com/hollowdoor/dom_autoscroller",
  "ignore": [
    ".jshintignore",
    ".gitignore",
    "README.md"
  ]
}
```

Put it in the root of the repo and then follow the steps here https://bower.io/docs/creating-packages/#register (best to have bower installed globally). You will need to tag your repo with a release version, I can't see any tags in the repo but the `package.json` file seems to be tagged as `v1.4.0`.

**Comment by hollowdoor** [comment]
It's published.
